# Generated by Django 3.2.5 on 2021-09-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
